// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include"NativeGameplayTags.h"


namespace WarriorGameplayTags
{
	/*Input Tags*/
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pause);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Block);
	/*Player Tags*/
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);

	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);

	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitReact);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Death);

	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitReact);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Death);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Block);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_PerfectBlock);

	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Hit);

	/*Player Status Tags (Internal - Not for UI Display)*/
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_PerfectBlockWindow);

	/*Data Tags*/
	ZHANSHI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
}


